department/function.yml
department/updateDepartment.js
empType/function.yml
empType/updateEmpType.js

API Name - updateDepartment
1. Updated updateDepartment.js API to include org_id in the response.
2.Corrected event body parsing to properly extract type and id from nested structure.
3.Refactored database queries to handle integer id values.
4.change the end the point remove the path
API Name - updateEmpType
1.Updated updateEmpType.js API to include org_id in the response.
2.Corrected event body parsing to properly extract type and id from nested structure.
3.Refactored database queries to handle integer id values.
4.change the end the point remove the path

feat: made minor changes

---

auth/function.yml
auth/userSignup.js

**API Name:**  UserSignup 
**Description :** This API is designed to handle user sign-up requests by creating users in Amazon Cognito, adding them to a specified user group, and updating their invitation status in a PostgreSQL database.
**Path:** /signup/{id}
**PathParam:** ( Employee Id ) required
**Response:**  
```{
"message": "Successfully Signed-up"
}
```

feat: Created UserSignup API

---

employee/addEmployee/addPersonalInfo.js
organisation/updateOrganization.js

**addPersonalInfo**
Made minor changes for addPersonalInfo. Made necessary fields as optional.

feat:made some fields of addPersonalInfo API as optional

---

employee/function.yml
employee/updatePersonalInfo.js
organization/function.yml
organization/updateOrganization.js
serverless.yml

1. Rename in the employee folder updateEmployee to updatePersonalInfo
2. Rename the folder name organisation to organization
3. Modified the serverless.yaml file as per folder names

feat:Rename the api names

---

auth/forgotpassword.js
auth/function.yml
auth/resetpassword.js

This API will helps user to reset the password 
Request body : 
````json
{
"email": "chetan",
"otp":" 596237",
"newPassword": "Synectiks@15"
}
````
Response 200 : 
````json
{
"message": "Password confirmed successfully"
}
````
Response 500: 
````json
{
"message": "error"
}
````

Resetpassword

---

auth/forgotpassword.js

This api will help the user to get the verification code to the user mail id after clicking the forgot password 
Request body: 
````json
{
"email": "chetan.meegada@synectiks.co"
}
````
Response : 200
````json
{
"message": "Password reset code sent successfully"
}
````
Response : 500
````json
{
"message": "error"
}
````

forgotpassword API

---

employee/employeeTracker.js
employee/function.yml

**API name:** employeeTracker [ with Pagination]
**Method:** get
**QueryStringParameter:** page [optional]
**Description:**  This api gets employee id, name, work_email, image, employee_type, designation, employee_status of all the employees. 
**API Response:** 
```json
{
"totalPages": 11,
"currentPage": 1,
"employees": [
{
"employee_name": "abduallah mohd",
"email": "abduallah@gmail.com",
"employee_status": "DRAFT",
"designation": "DevOps Engineer",
"employee_type": "Full-Time",
"image": ""
},
{
"employee_name": "adsdfsf dkfgdsjgjkdg",
"email": null,
"employee_status": "DRAFT",
"designation": null,
"employee_type": null,
"image": ""
},
{
"employee_name": "ahil khan",
"email": "ahil@gmail.com",
"employee_status": "DRAFT",
"designation": null,
"employee_type": null,
"image": …
```

feat:added API for employee tracking feature

---

employee/employeeTracker.js
employee/getEmployee.js
employee/getEmployees.js
employee/searchByName.js
employee/updatePersonalInfo.js
util/pathParamsValidator.js
util/queryParamsValidator.js

Refactored APIs for request body,query and path parameters validation & error-handling using middy middleware.

refactor:refactored APIs for validation & error-handling using middy

---

auth/signup.js
employee/getEmployee.js

Updated API sign-up and get employee

feat : Updated API sign-up and get employee

---

auth/InviteUser.js
auth/forgotPassword.js
auth/resetPassword.js
auth/signin.js
auth/signup.js
dashboard/dashboardStats.js
department/addDepartment.js
department/listDepartment.js
department/updateDepartment.js
designation/addDesignation.js
designation/updateDesignation.js
empType/addEmpType.js
empType/listEmpType.js
empType/updateEmpType.js
employee/addEmployee/addDocument.js
employee/addEmployee/addEquipmentdetailsInfo.js
employee/addEmployee/addPersonalInfo.js
employee/addEmployee/addProfessionalInfo.js
employee/employeeTracker.js
employee/getEmployee.js
employee/searchByName.js
employee/updatePersonalInfo.js
organization/updateOrganization.js
upload/docUpload.js

context) => {
context.callbackWaitsForEmptyEventLoop = false;

added context call back = false

---

auth/InviteUser.js
auth/function.yml
auth/newUserpassword.js
auth/signin.js
auth/signup.js

This api will helps in the reset the password of the user with new password new Userpassword API  and redirect tp the sin-in page of synectiks
request Body : 
````json
{
"email":"chetan.meegada@synectiks.com", 
"password":"n=4$b[R5<jjseD5%",
"newpassword":"Synectiks@1243"
}
````
response body 200 : 
````json
{
"message":" Password-Reset Successfully"
}
````

Updated API & new api newuserpassword

---

auth/function.yml
auth/refreshToken.js
auth/resetPassword.js

minor changes and new api refreshToken

 feat:minaor changes and new api refreshToken

---

auth/refreshToken.js

minor changes to refresh_token api

feat : minor changes to refreshtoken api

---

employee/function.yml
employee/scheduleInvite.js
package-lock.json
package.json

This AWS Lambda function acts as an API endpoint designed to facilitate the scheduling of invitations utilizing the AWS Scheduler service. The function is triggered by HTTP POST requests and operates within the AWS Lambda runtime environment.
**API Name:** ScheduleInvite 
**Method:** POST
**RequestBody:**
```
{
"timestamp":"2024-03-14T11:07:00",
"id": "bef36862-ff96-4b58-82ab-52b1dad5d8ec",
"invitation_status": "SCHEDULED"
}
```
**Responce:** 
```
{
"message": "user invited scheduled successfully at 2024-03-14T11:07:00"
}
```

feat:ScheduleInvite API for Invitation Scheduling

---

auth/newUserpassword.js
employee/inviteUser.js

** made minor changes in inviteUser api  , fixed invalidpassword generator error and added error handling userExistsException correctly**
** updated newUserPassword handler with middy and added functionality to update invitation_status to "ACTIVE" after succesfully
resetting the password **

feat:updated newUserPassword and inviteUser APIs

---

employee/deleteInvite.js
employee/function.yml
employee/scheduleInvite.js

**feat:** 
1. Added functionality to save scheduler details details in database in schedule API.
2. Created Delete Schedule API
**API Name**: deleteInvite
**Method:** DELETE
**QueryStringParameters:**
id = 3409d385-6802-4f9c-950a-cbae62fdb000 (employee id)
**Responce:**
```
{
"message": "user invite deleted successfully."
}
```

feat:Updated schedule API and created Delete Schedule API

---

auth/newUserpassword.js
employee/deleteInvite.js
employee/function.yml
employee/inviteUser.js
employee/updateInviteSchedule.js

**API name:** updateInviteSchedule 
**Method:** post
**requestBody:** 
```json
{
"timestamp":"2024-03-18T11:30:00",
"id": "7a015bd2-58d0-4a48-8849-e2dadb70c8fb"
}
```
**Description:**  This api updates the schedule time of an invite
**API Response:** 
```json
{
"message": "user invited scheduled successfully at 2024-03-18T11:30:00"
}
```

feat:added updateInviteSchedule API

---

dashboard/dashboardStats.js
department/addDepartment.js
department/listDepartment.js
department/updateDepartment.js
employee/addEmployee/addPersonalInfo.js
employee/deleteEmployee.js
employee/deleteInvite.js
employee/employeeTracker.js
employee/searchByName.js
organization/updateOrganization.js

included authorisation and added org_id from event

 included authorisation and added org_id from event

---

designation/addDesignation.js
designation/listDesignation.js
designation/updateDesignation.js
empType/addEmpType.js
empType/listEmpType.js
empType/updateEmpType.js
employee/getEmployee.js
employee/getEmployees.js
employee/inviteUser.js

Description: Adding org_id from designation and empType apis.

adding org_id from designation and empType

---

employee/employeeTracker.js

**employeeTracker**
**API Response**
```json
{
"totalPages": 1,
"currentPage": 1,
"employees": [
{
"id": "9c9291d7-b202-429d-b5b7-b04a9efc1ab9",
"employee_name": "Audrey Dudley",
"employee_status": "DRAFT",
"designation": null,
"employee_type": "full-half",
"image": "",
"first_name": "Audrey",
"last_name": "Dudley",
"dob": "2024-04-29T18:30:00.000Z",
"gender": "Male",
"number": "6514567890",
"email": "punug@mailinator.com",
"work_email": "fewivu@mailinator.com",
"highest_qualification": "Commodi ut doloremqu"
},
{
"id": "4607d5b4-c613-43bf-a6a4-0d04ad1f1404",
"employee_name": "dfv vfdc",
"employee_status": "DRAFT",
"designation": null,
"employee_type": "full-half",
"image": "https://workflow-lambda-dev-serverlessdeploymentbucket-ygpfd8ufe19x.s3.amazonaws.com/workflow_DMS/screenshot2023-08- …
```

added required fields in the response

---

employee/getEmployee.js
employee/getEmployees.js

**made minor change in API response to include work_email field in organizational details object.**

minor change in API response

---

employee/addEmployee/addDocument.js
employee/addEmployee/uploadDocs.js

**Added type field on insert query of addDocument  API for type of document been uploaded,
added uploadDocs function to add document to S3 bucket**

added uploadDocs,modified addDocument API's

---

auth/signin.js

minor: solved the sign-in issue
